# Site settings
course_name: Modern Cryptography
course_description: "This is a basic course on Modern Cryptography, designed for undergraduate students at Indian universities and institutes. One of the goals of this course is to equip students with the confidence to create public key and secret key pairs, and to use them effectively."

course_semester: "Fall 2025"

#baseurl: "/~shashank/crypto25" # the subpath of your site, e.g. /blog/
#url: "http://localhost/~shashank" # the base hostname & protocol for your site

baseurl: "/crypto25" # the subpath of your site, e.g. /blog/
url: "http://drshashanksingh.github.io/" # the base hostname & protocol for your site

schoolname: "TEACHING"
schoolurl: "https://drshashanksingh.github.io/crypto25/"
#twitter_username: username 

address: |
    Electrical Engineering & Computer Science 
    IISERB, Bhopal
    India

# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
# google_analytics: UA-XXXXXXXX-X

# Set your ClustrMaps ID (set up yours at http://www.clustrmaps.com/)
clustrmaps: BJm4TijpLW5G_cIduNR-mtJWySd1dzzVJHT4lAV8jqo
enable_clustrmaps_icon: true 
clustrmaps_id: 1c7l3

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%m/%d/%Y"

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false
    homeworks:
        output: true


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
## shashank
  - scope:
      path: ""
      type: "homeworks"
    values: 
      layout: "homework"
## Shashank
default_og_image: /_images/logo.png
